---
title: "Chinese Zodiac"
author: "Lee Bee Yin"
date: "February 26, 2016"
output: slidy_presentation
---

## Chinese Zodiac Calculator

Using this calculator, you can easily find out your Chinese Zodiac and your best match!

In line with the Chinese New Year around the corner, I thought this would be a great fun calculator for you to try to understand one of the Chinese traditions.  What is more fun then to know your Chinese Zodiac and your best match?  Chinese Zodiac is similar to horoscopes known in the west.  But, Chinese Zodiac are made up of animal signs from Rat to Pig.

With the Chinese Zodiac, you would be able to know and understand yourself more. (or wouldn't it?)
The Chinese Zodiac is determined by the year you are born.

*Note: This is an estimation because your zodiac may differs if you are born in January or February.*

## List of Chinese Zodiac (in order)

    - Rat
    - Ox
    - Tiger
    - Rabbit
    - Dragon
    - Snake
    - Horse
    - Goat
    - Monkey
    - Rooster
    - Dog
    - Pig

## Steps:

The calculator is just easy to use.

Enter the year your are born and click Submit.

You will be able to see your Chinese Zodiac and your best match.

You may even key in anyone's year if you are curious.


## Slide with R Code 

```{r}
zodiac <- function(year) {
  x <- year%%12
  if (x == 0) {
    print("Monkey.  Your best match are Snake, Dragon, Rat")
  } else if (x == 1) {
    print("Rooster.  Your best match are Dragon, Ox, Snake")
  } else if (x == 2) {
    print("Dog.  Your best match are Rabbit, Horse, Tiger")
  } else if (x == 3) {
    print("Pig.  Your best match are Tiger, Rabbit, Goat")
  } else if (x == 4) {
    print("Rat.  Your best match are 	Ox, Dragon, Monkey")
  } else if (x == 5) {
    print("Ox.  Your best match are Rat, Rooster, Snake")
  } else if (x == 6) {
    print("Tiger.  Your best match are Pig, Horse, Dog")
  } else if (x == 7) {
    print("Rabbit.  Your best match are 	Dog, Pig, Goat")
  } else if (x == 8) {
    print("Dragon.  Your best match are Rooster, Monkey, Rat")
  } else if (x == 9) {
    print("Snake.  Your best match are Monkey, Rooster, Ox")
  } else if (x == 10) {
    print("Horse.  Your best match are 	Goat, Dog, Tiger")
  } else if (x == 11) {
    print("Goat.  Your best match are Horse, Rabbit, Pig")
  } else
    print("Error")
}
```

